name: build-test-release

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3
    - uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: cargo test
      uses: actions-rs/cargo@v1
      with:
        command: test
    - name: cargo build --release
      uses: actions-rs/cargo@v1
      with:
        command: build --release
    - name: Upload for release
      uses: actions/upload-artifact@v3
      with:
        name: actions-playground-${{ runner.os }}-${{ runner.arch }}
        path: target/release/actions-playground
  publish:
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
    - uses: actions/download-artifact@v3
      with:
        name: actions-playground-*
    - name: List downloaded artifacts
      runs: ls -la
    - name: Publish GitHub release
      uses: softprops/action-gh-release@v1
      with:
        body_path: ${{ github.workspace }}/RELEASE-NOTES.txt
        files: actions-playground-*
