name: build-test-release

on: push

env:
  CARGO_TERM_COLOR: always

jobs:
  test-build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - name: cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test
      - name: cargo build --release
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release
      - name: Upload for release
        uses: actions/upload-artifact@v3
        with:
          name: actions-playground-${{ runner.os }}-${{ runner.arch }}
          path: target/release/actions-playground
      - name: Upload for release, Windows
        uses: actions/upload-artifact@v3
        if: ${{ runner.os == 'Windows' }}
        with:
          name: actions-playground-${{ runner.os }}-${{ runner.arch }}.exe
          path: target/release/actions-playground.exe
  publish:
    needs: test-build
    if: startsWith(github.ref, 'refs/tags/v') || contains(github.event.push.head_commit.message, '!citestrun')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          path: artifacts
      - name: List downloaded artifacts
        run: ls -Rla
      - run: echo Released ${{ github.ref_name }} > RELEASE-NOTES.txt
      - name: Publish GitHub release
        uses: softprops/action-gh-release@v1
        with:
          body_path: ${{ github.workspace }}/RELEASE-NOTES.txt
          # download-artifact puts artifacts in separate directories if no name specified
          files: 'artifacts/actions-playground*'
